pokemon/home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
]

pokemon/pokedex/urls.py
from django.urls import path

from . import views

app_name = "pokedex"

urlpatterns = [
    path("", views.PokemonListView.as_view(), name="pokemon_list"),
    path("create/<str:pokemon_name>", views.createPokemon, name="pokemon_create"),
    path("loadInitialData", views.loadInitialData, name="initial_create"),
    path("getInfo/<int:pk>", views.PokemonDetailView.as_view(), name="pokemon_detail"),
    path("delete/<int:pk>", views.PokemonDeleteView.as_view(), name="pokemon_delete"),
]

pokemon/pokemon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pokedex/',include('pokedex.urls', namespace='pokedex')),
    path('home/', include('home.urls', namespace='home')),
    path('type/', include('type.urls', namespace='type')),
    path('', include('home.urls', namespace="home")),
]

pokemon/type/urls.py
from django.urls import path

from . import views

app_name = "type"

urlpatterns = [
    path("", views.TypeListView.as_view(), name="type_list"),
    path("getInfo/<int:pk>", views.TypeDetailView.as_view(), name="type_detail"),
    path("battle/<int:first_id>/<int:second_id>", views.battlePokemon, name="pokemon_battle")
]

pokemon/pokedex/models.py
from django.db import models

# Create your models here.
class Type(models.Model):
    name = models.CharField(max_length=50)
    damage_relations = models.JSONField(default=list)

class Pokemon(models.Model):
    name = models.CharField(max_length=100)
    hp = models.SmallIntegerField()
    attack = models.SmallIntegerField()
    defense = models.SmallIntegerField()
    special_attack = models.SmallIntegerField()
    special_defense = models.SmallIntegerField()
    speed = models.SmallIntegerField()
    image = models.CharField(max_length=250)
    type = models.ManyToManyField(Type)
    
    class Meta:
        ordering = ['name']
        
    def __str__(self):
    		return self.name

class PokemonNames(models.Model):
    name = models.CharField(max_length=100)

pokemon/pokedex/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.http import HttpResponse

from .models import Pokemon, Type, PokemonNames

import json
import http.client
import requests

# Create your views here.

class PokemonListView(ListView):
    model = Pokemon

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pokemon_names'] = PokemonNames.objects.all()
        return context

class PokemonDetailView(DetailView):
    model = Pokemon

class PokemonDeleteView(DeleteView):
    model = Pokemon
    success_url = reverse_lazy("pokedex:pokemon_list")
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Pokemon "{pokemon_name}" has been deleted'.format(
                pokemon_name=self.object.name.capitalize()))
        return response
    
def createPokemon(request, pokemon_name):
    api_url = 'https://pokeapi.co/api/v2/pokemon/{fname}'.format(fname = pokemon_name)
    response = requests.get(api_url)

    if response.status_code == 200:
        pokemon_data = response.json()
        if Pokemon.objects.filter(name=pokemon_data['name']).exists():
            messages.add_message(
                request, messages.ERROR,
            'Pokemon "{pname}" already exists.'.format(pname=pokemon_data['name'].capitalize()))
        else:
            current_pokemon = Pokemon(
                name = pokemon_data['name'],
                hp = pokemon_data['stats'][0]['base_stat'],
                attack = pokemon_data['stats'][1]['base_stat'],
                defense = pokemon_data['stats'][2]['base_stat'],
                special_attack = pokemon_data['stats'][3]['base_stat'],
                special_defense = pokemon_data['stats'][4]['base_stat'],
                speed = pokemon_data['stats'][5]['base_stat'],
                image = pokemon_data['sprites']['front_default']
            )
            current_pokemon.save()
            for i in pokemon_data['types']:
                type_name = i['type']['name']
                try:
                    current_type = Type.objects.get(name=type_name)
                except:
                    messages.add_message(
                        request, messages.ERROR,
                    'Please load types before adding Pokemon')
                    return redirect("pokedex:pokemon_list")
                current_pokemon.type.add(current_type)
            current_pokemon.save()

            messages.add_message(
                request, messages.SUCCESS,
            'Pokemon "{pname}" successfully added.'.format(pname = pokemon_data['name'].capitalize()))
    else:
        messages.add_message(
                request, messages.ERROR,
            'Please enter a valid Pokemon name.')

    return redirect("pokedex:pokemon_list")

def loadInitialData(request):
    if len(Type.objects.filter()) == 0:
        for i in range(18):
            current_num = i + 1
            api_url = 'https://pokeapi.co/api/v2/type/{tnum}'.format(tnum = current_num)
            response = requests.get(api_url)
            type_data = response.json()

            current_type = Type(
                name = type_data['name'],
                damage_relations = type_data['damage_relations']
            )
            current_type.save()
        messages.add_message(
            request, messages.SUCCESS,
            'Successfully loaded all Types.'
        )
    else:
        messages.add_message(
            request, messages.ERROR,
            'Types are already loaded.'
        )

    for i in range(9):
        current_poke_num = i + 1
        api_url = 'https://pokeapi.co/api/v2/pokemon/{pnum}'.format(pnum = current_poke_num)
        response = requests.get(api_url)
        pokemon_data = response.json()
        if Pokemon.objects.filter(name=pokemon_data['name']).exists():
            messages.add_message(
                request, messages.ERROR,
            'Pokemon "{pname}" already exists.'.format(pname=pokemon_data['name'].capitalize()))
        else:
            current_pokemon = Pokemon(
                name = pokemon_data['name'],
                hp = pokemon_data['stats'][0]['base_stat'],
                attack = pokemon_data['stats'][1]['base_stat'],
                defense = pokemon_data['stats'][2]['base_stat'],
                special_attack = pokemon_data['stats'][3]['base_stat'],
                special_defense = pokemon_data['stats'][4]['base_stat'],
                speed = pokemon_data['stats'][5]['base_stat'],
                image = pokemon_data['sprites']['front_default']
            )
            current_pokemon.save()
            for i in pokemon_data['types']:
                type_name = i['type']['name']
                try:
                    current_type = Type.objects.get(name=type_name)
                except:
                    messages.add_message(
                        request, messages.ERROR,
                    'Please load types before adding Pokemon')
                    return redirect("pokedex:pokemon_list")
                current_pokemon.type.add(current_type)
            current_pokemon.save()

    if len(PokemonNames.objects.filter()) == 0:
        api_url = 'https://pokeapi.co/api/v2/pokemon?limit=100000&offset=0'
        response = requests.get(api_url)
        pname_data = response.json()
        results = pname_data['results']
        for result in results:
            current_name = PokemonNames(
                name = result['name']
            )
            current_name.save()
        messages.add_message(
            request, messages.SUCCESS,
            'Pokemon names are loaded.'
        )
    else:
        messages.add_message(
            request, messages.ERROR,
            'Pokemon names are already loaded.'
        )

    return redirect("pokedex:pokemon_list")

pokemon/pokedex/templates/pokedex/pokemon_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
<title>Confirm Delete</title>
<form method="post">{% csrf_token %}
    <br><br>
    <h5 class="display-6"><strong>Are you sure you want to delete the Pokemon "{{ object.name|title }}"?</strong></h5>
    {{ form.as_p }}
    <input type="submit" value="Confirm" class="btn btn-primary">
    <a href="{% url 'pokedex:pokemon_detail' object.id %}" class="btn btn-danger">Go back</a><br/>
</form>
</div>
{% endblock content %}

pokemon/pokedex/templates/pokedex/pokemon_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container">
<title>{{object.name|title}}</title>
<br>
<a href="{% url 'pokedex:pokemon_list' %}" class="btn btn-primary">Go back to Pokemon list</a><br/><br/>
<a href="{% url 'pokedex:pokemon_delete' object.id %}" class="btn btn-danger">Delete Pokemon</a><br/><br/>

<table class="table table-bordered" style="opacity: 0.9;">
    <tr class="table-info">
    <th>Name</th>
    <th>Image</th>
    <th>Type</th>
    <th>HP</th>
    <th>ATK</th>
    <th>DEF</th>
    <th>SP_ATK</th>
    <th>SP_DEF</th>
    <th>SPD</th> 
    </tr>
    <tr>
    <td>{{object.name|title}}</td>
    <td><img src="{{object.image}}"></td>
    <td>{% for type in object.type.all %}<a href="{% url 'type:type_detail' type.id %}">{{ type.name|title }}</a><br>{% endfor %}</td>
    <td>{{object.hp}}</td>
    <td>{{object.attack}}</td>
    <td>{{object.defense}}</td>
    <td>{{object.special_attack}}</td>
    <td>{{object.attack}}</td>
    <td>{{object.speed}}</td> 
</table>
</div>
{% endblock content %}

pokemon/pokedex/templates/pokedex/pokemon_list.html
{% extends "base.html" %}

{% block content %}
<title>Pokedex</title>
<br>
<div class="container">
    <div class="row">
        <div class="col">
            <div>
                <input class="form-control" type="text" placeholder="Search.." id="myInput" onkeyup="filter()"><br>
                <select class="form-select" id="showPokemon">
                    {% for name_object in pokemon_names %}
                    <option class="pokelist {{name_object.name}}" id="{{name_object.name}} {{name_object.id}}"value={{name_object.name}}>{{name_object.name|title}}</option>
                    {% endfor %}
                </select>
                <div class="col">
                    <button class="col btn btn-secondary" id="addToPokedex">Add to Pokedex</a></button>
                    <a href="http://127.0.0.1:8000/pokedex/loadInitialData" class="btn btn-secondary">Load Initial Data</a>
                    
                </div>
            </div>
        </div>
        <br>
    </div>

<table class="table table-bordered table-striped table-hover" style="opacity: 0.9;">
    <tr class="table-info">
    <th>Name</th>
    <th>Image</th>
    {% comment %} <th>HP</th>
    <th>ATK</th>
    <th>DEF</th>
    <th>SP_ATK</th>
    <th>SP_DEF</th>
    <th>SPD</th> {% endcomment %}
    </tr>
{% for pokemon in object_list %}
    <tr> 
    <td><a href="{% url 'pokedex:pokemon_detail' pokemon.id %}" class="btn btn-link" data-bs-toggle="tooltip" title="View data?">{{pokemon.name|title }}</a></td>
    <td><img src="{{pokemon.image}}"></td>
    </tr>
    {% comment %} <td>{{pokemon.hp}}</td>
    <td>{{pokemon.attack}}</td>
    <td>{{pokemon.defense}}</td>
    <td>{{pokemon.special_attack}}</td>
    <td>{{pokemon.attack}}</td>
    <td>{{pokemon.speed}}</td> {% endcomment %}
{% endfor %}
</table>
</div>
</div>
{% endblock content %}

{% comment %} class Pokemon(models.Model):
    name = models.CharField(max_length=25)
    hp = models.SmallIntegerField()
    attack = models.SmallIntegerField()
    defense = models.SmallIntegerField()
    special_attack = models.SmallIntegerField()
    special_defense = models.SmallIntegerField()
    speed = models.SmallIntegerField()
    image = models.CharField(max_length=250)
    type = models.ManyToManyField(Type)
    
    class Meta:
        ordering = ['name']
        
    def __str__(self):
    		return self.name {% endcomment %}