pokemon/home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
]

pokemon/pokemon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pokedex/',include('pokedex.urls', namespace='pokedex')),
    path('home/', include('home.urls', namespace='home')),
    path('type/', include('type.urls', namespace='type')),
    path('', include('home.urls', namespace="home")),
]

pokemon/type/urls.py
from django.urls import path

from . import views

app_name = "type"

urlpatterns = [
    path("", views.TypeListView.as_view(), name="type_list"),
    path("getInfo/<int:pk>", views.TypeDetailView.as_view(), name="type_detail"),
    path("battle/<int:first_id>/<int:second_id>", views.battlePokemon, name="pokemon_battle")
]

pokemon/type/models.py
from django.db import models

# Create your models here.

pokemon/type/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.http import HttpResponse
from pokedex.models import Type, Pokemon

import json
import http.client
import requests

# Create your views here.
class TypeListView(ListView):
    model = Type
    template_name = "type/type_list.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_pokemon'] = Pokemon.objects.all()
        return context

class TypeDetailView(DetailView):
    model = Type
    template_name = "type/type_detail.html"

def battlePokemon(request, first_id, second_id):
    first_pokemon = Pokemon.objects.get(id=first_id)
    second_pokemon = Pokemon.objects.get(id=second_id)

    pokemon_context = {}
    pokemon_context["p1types"] = {}
    pokemon_context["p2types"] = {}

    for ptype in first_pokemon.type.all():
        type_name = ptype.name
        current_multiplier = 1
        info_string = ""
        for ptype in second_pokemon.type.all():
            current_relations = ptype.damage_relations
            for i in current_relations['double_damage_from']:
                if type_name == i['name']:
                    current_multiplier = current_multiplier * 2
            for i in current_relations['half_damage_from']:
                if type_name == i['name']:
                    current_multiplier = current_multiplier * 0.5
            for i in current_relations['no_damage_from']:
                if type_name == i['name']:
                    current_multiplier = current_multiplier * 0
        
        if current_multiplier == 0:
           info_string = type_name.capitalize() + " does no damage against " + second_pokemon.name.capitalize() + "."
        else:
            info_string = type_name.capitalize() + " does " + str(current_multiplier) + " times damage against " + second_pokemon.name.capitalize() + "."
        pokemon_context["p1types"][type_name] = info_string
    
    for ptype in second_pokemon.type.all():
        type_name = ptype.name
        current_multiplier = 1
        info_string = ""
        for ptype in first_pokemon.type.all():
            current_relations = ptype.damage_relations
            for i in current_relations['double_damage_from']:
                if type_name == i['name']:
                    current_multiplier = current_multiplier * 2
            for i in current_relations['half_damage_from']:
                if type_name == i['name']:
                    current_multiplier = current_multiplier * 0.5
            for i in current_relations['no_damage_from']:
                if type_name == i['name']:
                    current_multiplier = current_multiplier * 0
        
        if current_multiplier == 0:
           info_string = type_name.capitalize() + " does no damage against " + first_pokemon.name.capitalize() + "."
        else:
            info_string = type_name.capitalize() + " does " + str(current_multiplier) + " times damage against " + first_pokemon.name.capitalize() + "."
        pokemon_context["p2types"][type_name] = info_string
    
    context = {
        'type_context': pokemon_context,
        'p1_name': first_pokemon.name.capitalize(),
        'p1_image': first_pokemon.image,
        'p2_name': second_pokemon.name.capitalize(),
        'p2_image': second_pokemon.image,
    }
    return render(request, 'type/battle.html', context)

pokemon/type/templates/type/battle.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container" style="opacity:0.9;">
<title>{{p1_name}} vs. {{p2_name}}</title>
<br>
<a class="btn btn-secondary" href="{% url 'type:type_list' %}">Go back to Type list</a><br/><br/>
<h1 class="text-center bg-danger border rounded"><img src="{{p1_image}}"><b> {{p1_name}} vs. {{p2_name}} </b> <img src="{{p2_image}}"> </h1>
<h2 class="text-center bg-light border rounded">{{p1_name}}'s types against {{p2_name}}</h2>
<p class="container bg-light rounded border">
    {% for type, info in type_context.p1types.items %}
        <img src="/static/{{type}}.png"> {{info}} <img src="{{p2_image}}"> <br>
    {% endfor %}
</p>
<h2 class="text-center bg-light border rounded">{{p2_name}}'s types against {{p1_name}}</h2>
<p class="container bg-light rounded border">
    {% for type, info in type_context.p2types.items %}
        <img src="/static/{{type}}.png"> {{info}} <img src="{{p1_image}}"> <br>
    
        {% endfor %}
</p>
<div>
{% endblock content %}

pokemon/type/templates/type/type_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container">
<title>{{object.name|title}}</title>
<br>
<a class="btn btn-secondary" href="{% url 'type:type_list' %}">Go back to Type list</a><br/><br/>

<h1 class="text-center"><img src="/static/{{object.name}}.png"> {{object.name | title}} Type Information <img src="/static/{{object.name}}.png"> </h1> <br>
<table class="table table-image table-bordered table-striped" style="opacity:0.9;">
    <tr>
        <th class="table-success"><h2>Advantages</h2></th>
        <th class="table-danger"><h2>Disadvantages</h2></th>
    </tr>
    <tr>
        <td> 
            <h5>Double damage to: </h5>
                {% for i in object.damage_relations.double_damage_to %}
                    {{i.name | title }} <img src="/static/{{i.name}}.png" style="max-width:20%;"> <br>
                    {% empty %}
                    None
                {% endfor %}
        </td>
        <td> 
            <h5>Double damage from: </h5>
                {% for i in object.damage_relations.double_damage_from %}
                    {{i.name | title }} <img class="img-fluid" src="/static/{{i.name}}.png" style="max-width:20%;"> <br>
                    {% empty %}
                    None
                {% endfor %}
        </td>
    </tr>
    <tr>
        <td> 
            <h5>Half damage from: </h5>
                {% for i in object.damage_relations.half_damage_from %}
                    {{i.name | title }} <img src="/static/{{i.name}}.png" style="max-width:20%;"> <br>
                    {% empty %}
                    None
                {% endfor %}
        </td>
        <td> 
            <h5>Half damage to: </h5>
                {% for i in object.damage_relations.half_damage_to %}
                    {{i.name | title }} <img src="/static/{{i.name}}.png" style="max-width:20%;"> <br>
                    {% empty %}
                    None
                {% endfor %}
        </td>
    </tr>
    <tr>
        <td> 
            <h5>No damage from: </h5>
            {% for i in object.damage_relations.no_damage_from %}
                {{i.name | title }} <img src="/static/{{i.name}}.png" style="max-width:20%;"> <br>
                {% empty %}
                None
            {% endfor %}
        </td>
        <td> 
            <h5>No damage to: </h5>
            {% for i in object.damage_relations.no_damage_to %}
                {{i.name | title }} <img src="/static/{{i.name}}.png" style="max-width:20%;"> <br>
                {% empty %}
                None
            {% endfor %}

        </td>
    </tr>
</table>
<div>

{% endblock content %}

pokemon/type/templates/type/type_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
<title>Type</title>
<br>
Pokemon 1:
<div class="col-6">
<select class="form-select" id="pokemon1">
    {% for pokemon in current_pokemon %}
        <option value={{pokemon.id}}>{{pokemon.name|title}}</option>
    {% endfor %}
</select>
</div>
<br>
Pokemon 2:
<div class="col-6">
<select class="form-select" id="pokemon2">
    {% for pokemon in current_pokemon %}
        <option value={{pokemon.id}}>{{pokemon.name|title}}</option>
    {% endfor %}
</select>
</div>
<button class="col btn btn-secondary" id="battlePokemon">Battle Pokemon</button>

<br>
<br>
<table class="table table-bordered table-striped" style="opacity: 0.9;"> 
    <tr class="table-info">
    <th>Type</th>
    <th>Image</th>
    </tr>
    {% for type in object_list %}
    <tr>
    <td><a class="btn btn-link" data-bs-toggle="tooltip" title="View data?" href="{% url 'type:type_detail' type.id %}">{{ type.name|title }}</a></td>
    <td> <img src="/static/{{type.name}}.png"></td>
    </tr>
    {% endfor %}

</table>
</div>
{% endblock content %}